#!/usr/bin/env python3
"""Balance measurement driver (TEST_PLAN Section L, rows 161-199).

gen: write harness scenario files that measure one profession: N repeats per (base skill, gear bonus)
     point, one fixed game-time window each, at speed 10. Two kinds of job:
       craft      a CraftingBuilding: crafts queued at the bench; result = queue drop in the window
       operate    a ProductionBuilding/farm: result = pg_operate output_progress (fractional units)
     Each window ends with an `@echo BAL,...` line.
csv: turn the BAL lines of one or more runner .out files into the CSV tools/analyze_balance.py reads
     (test_id,profession,base_skill,effective_bonus_pct,elapsed_game_seconds,result_count,valid,gear_loadout,notes).

Usage:
  python3 tools/balance_driver.py gen            (rewrites tests/ingame/full-base/pg-5x-balance-*.txt)
  python3 tools/balance_driver.py csv run.out... > balance.csv
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "tests", "ingame", "full-base")
PG_LOG = r"D:\Steam\steamapps\common\Kenshi\mods\ProfessionGearProgression\ProfessionGear.log"

# Fixture Testing-Save-Full-Base: squad Beaks + Avarek. The worker is Avarek, Beaks stays the selection.
WORKER = "Avarek"
OTHER = "Beaks"

# One entry per profession file. bench/item names: partial names as `benches`/`craft ... at` accept.
# gear: (label, pg stat, pct). "lab50" is the control: Labouring gear must NOT speed up a non-Labouring job
# (PG scales ProductionBuilding::operate with Labouring; CraftingBuilding derives from ProductionBuilding).
PROFESSIONS = [
    dict(file="pg-52-balance-weapon-smithing.txt", rows="188 (+ 145/229 data: the Sickle)", kind="craft",
         profession="weapon_smithing", setstat="weapon_smith", pgstat="weapon_smithing",
         bench="Weapon", item="Sickle", give=[("Iron Plates", 15)],
         prep=['research "Basic Weapon Smithing"', 'research "Basic Weapon Grades"', 'research "Utility Weapons"'],
         check=r'benches 400 crafts ~ Weapon[^|]*Sickle'),
    dict(file="pg-53-balance-armour-smithing.txt", rows="189", kind="craft",
         profession="armour_smithing", setstat="armour_smith", pgstat="armour_smithing",
         bench="Clothing", item="Rag Shirt", give=[("584-gamedata.base", 15)],
         prep=['blueprint "Rag Shirt"'], check=r'benches 400 crafts ~ Clothing[^|]*Rag Shirt'),
]

SKILLS_ONCE = [10, 90]       # no gear, one window each: the skill curve end points
BASE = 50                    # the gear points are measured at this skill
GEAR = [("none", None, 0), ("own50", "OWN", 50), ("lab50", "labouring", 50)]
REPEATS = 3
WINDOW_MIN = 10
GEAR_ITEM = "Iron Hat"       # given + equipped at the start; its affix is forced per window


def header(p):
    n_windows = len(SKILLS_ONCE) + REPEATS * len(GEAR)
    return [
        "# id: PG-%s" % os.path.splitext(p["file"])[0],
        "# covers: PG %s (Section L balance sweep, generated by tools/balance_driver.py gen; edit the generator, not this file)" % p["rows"],
        "# fixture: Testing-Save-Full-Base (squad %s + %s)" % (OTHER, WORKER),
        "# reset: fresh",
        "# needs: ProfessionGearProgression.dll 7D80DBB3 (JobOperateScaling on), harness 08AB6BF0; set_test_mode.ps1 -Mode Forced -Rules InGameTest",
        "# design: %d windows of %d game min at speed 10: skill %s without gear, then %d x (skill %d: no gear / +50%% %s / +50%% Labouring control)."
        % (n_windows, WINDOW_MIN, "/".join(map(str, SKILLS_ONCE)), REPEATS, BASE, p["profession"]),
        "#   10 %s crafts are queued before every window; result = queue drop in the window (a drop of 10 = saturated:" % p["item"],
        "#   tell the PG agent to shorten the window). The gear is an %s given to and worn by the worker." % GEAR_ITEM,
        "# verify: every window has a BAL line with queue values; at least one craft per no-gear window at skill 50 (else the",
        "#   window is too short: tell the PG agent). Data: python3 tools/balance_driver.py csv <out> > balance.csv, then",
        "#   tools/analyze_balance.py. lab50 should equal none (else Labouring leaks into this job); own50 > none means the job",
        "#   reads the hooked %s." % p["profession"],
    ]


def window(p, label, skill, gear_label, stat, pct, rep):
    lines = ["# --- %s: skill %d, gear %s, repeat %d ---" % (label, skill, gear_label, rep),
             "setstat %s %s %d" % (WORKER, p["setstat"], skill),
             "pg_clear %s ~ cleared affixes" % WORKER]
    if stat:
        s = p["pgstat"] if stat == "OWN" else stat
        lines.append('pg_force_affix %s "%s" %s %d tier 6 ~ affixes=' % (WORKER, GEAR_ITEM, s, pct))
        lines.append("pg_bonus %s %s ~ equipped_bonus=%d%% .*match=1" % (WORKER, s, pct))
    for item, n in p["give"]:
        lines.append('give %s "%s" %d' % (WORKER, item, n))
    lines += ['craft %s "%s" at "%s" count 10 ~ queued' % (WORKER, p["item"], p["bench"]),
              '@set Q0 benches 400 ~ %s[^|]*queue=(\\d+)' % p["bench"],
              "speed 10",
              "@wait-game %d 900" % WINDOW_MIN,
              "speed 0",
              '@set Q1 benches 400 ~ %s[^|]*queue=(\\d+)' % p["bench"],
              "@echo BAL,%s,%s,%d,%d,%d,${Q0},${Q1},%s,%s"
              % (p["rows"].split()[0], p["profession"], skill, pct if stat == "OWN" else 0, WINDOW_MIN * 60,
                 gear_label, label),
              "hunger %s 280" % WORKER]
    return lines


def gen():
    os.makedirs(OUT_DIR, exist_ok=True)
    for p in PROFESSIONS:
        L = header(p) + [
            "@wait-world", "@sleep 8", "speed 0",
            "protect %s on" % OTHER, "protect %s on" % WORKER,
            "hunger %s 280" % WORKER, "hunger %s 280" % OTHER,
            "select %s" % OTHER,
        ] + p["prep"] + [
            p["check"],
            "clearjobs %s" % WORKER,
            # the gear carrier: a hat given and worn for the whole run (its affix is forced per window)
            'give %s "%s" 1' % (WORKER, GEAR_ITEM),
            'equip %s "%s"' % (WORKER, GEAR_ITEM),
            'pg_info %s "%s" ~ equipped=1' % (WORKER, GEAR_ITEM),
        ]
        rep_label = 0
        for s in SKILLS_ONCE:
            rep_label += 1
            L += window(p, "w%d" % rep_label, s, "none", None, 0, 1)
        for r in range(1, REPEATS + 1):
            for g in GEAR:
                rep_label += 1
                L += window(p, "w%d" % rep_label, BASE, g[0], g[1], g[2], r)
        L += ["clearjobs %s" % WORKER]
        path = os.path.join(OUT_DIR, p["file"])
        with open(path, "w", newline="\n") as fh:
            fh.write("\n".join(L) + "\n")
        print("wrote", path)


def to_csv(paths):
    print("test_id,profession,base_skill,effective_bonus_pct,elapsed_game_seconds,result_count,valid,gear_loadout,notes")
    for path in paths:
        for line in open(path, encoding="utf-8", errors="replace"):
            m = re.search(r"=> BAL,([^,]+),([^,]+),(\d+),(\d+),(\d+),(\d*),(\d*),([^,]+),(\S+)", line)
            if not m:
                continue
            tid, prof, skill, bonus, secs, q0, q1, gear, label = m.groups()
            ok = q0 != "" and q1 != ""
            done = int(q0) - int(q1) if ok else 0
            gear_bonus = 50 if gear == "lab50" else int(bonus)
            print("%s,%s,%s,%s,%s,%d,%d,%s,%s" % (tid, prof, skill, bonus, secs, done, 1 if ok else 0, gear,
                                                 "%s gear_pct=%d %s" % (label, gear_bonus, os.path.basename(path))))


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "gen":
        gen()
    elif len(sys.argv) >= 3 and sys.argv[1] == "csv":
        to_csv(sys.argv[2:])
    else:
        print(__doc__)
        sys.exit(2)
